name: adiyogtap
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  cached_network_image: ^3.3.0
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.1.0
  google_fonts: ^6.1.0
  http: ^1.1.0
  webview_flutter: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/bg/1.png
    - assets/bg/2.png
    - assets/bg/3.png
    - assets/bg/4.png
    - assets/bg/5.png
    - assets/bg/6.png
